name:                citygml4hs
version:             0.1.0.0
github:              "ennioVisco/citygml4hs"
license:             BSD3
author:              "Ennio Visconti"
maintainer:          "ennio.visconti@mail.polimi.it"
copyright:           "2018 Ennio Visconti"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ennioVisco/citygml4hs#readme>

dependencies:
- base >= 4.7 && < 5
- hxt

library:
  source-dirs: src

tests:
  citygml4hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - citygml4hs
